FROM nginx:alpine

# Copy the React production build
COPY build /usr/share/nginx/html

# Copy SSL certificates
COPY ../docker/ssl/spa.crt /etc/ssl/certs/spa.crt
COPY ../docker/ssl/spa.key /etc/ssl/private/spa.key

# Copy custom nginx configuration
COPY nginx-production.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
